name: ingestion
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - argparse=1.4.0
  - blas=1.0=mkl
  - bzip2=1.0.8
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - curl=7.71.1
  - intel-openmp=2019.4
  - krb5=1.18.2
  - ld_impl_linux-64
  - libcurl=7.71.1
  - libdeflate=1.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran-ng
  - libssh2=1.9.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.4
  - ncurses=6.2
  - numpy=1.17.0
  - numpy-base=1.17.0
  - openssl=1.1.1i
  - pandas=1.1.3
  - pip=20.3.1
  - pysam=0.15.3
  - python=3.6.12
  - python-dateutil=2.8.1
  - pytz=2020.4
  - pyvcf=0.6.8
  - readline=8.0
  - setuptools=51.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.1
  - xz=5.2.5
  - zlib=1.2.11
