name: snv_bench
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bcftools=1.9
  - bedtools=2.29.2
  - blas=1.0
  - bx-python=0.7.3
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - certifi=2020.6.20
  - click=7.1.2
  - coloredlogs=10.0
  - curl=7.69.1
  - cython=0.29.14
  - cyvcf2=0.11.6
  - hap.py=0.3.10
  - htslib=1.9
  - humanfriendly=4.18
  - intel-openmp=2020.2
  - krb5=1.17.1
  - libcurl=7.69.1
  - libdeflate=1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libssh2=1.9.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - nose=1.3.7
  - numpy=1.16.6
  - numpy-base=1.16.6
  - openssl=1.1.1j
  - pandas=0.24.2
  - pip=19.3.1
  - pybedtools=0.8.1
  - pysam=0.15.3
  - python=2.7.17
  - python-dateutil=2.8.1
  - python_abi=2.7
  - pytz=2021.1
  - pyvcf=0.6.8
  - readline=7.0
  - samtools=1.9
  - scipy=1.2.1
  - setuptools=44.0.0
  - six=1.15.0
  - sqlite=3.31.1
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11

